name: Backend Prod Deployment

on:
  push:
    branches: [main] 

jobs:
  backend-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      # As the program becomes more robust move to backend folder and run all the servers and tests
      - name: Install about 
        working-directory: features/backend/about_service
        run: | 
          npm install
          
      - name: Install application
        working-directory: features/backend/application_service
        run: | 
          npm install
          
      - name: Deploy backend to cloud
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/S26-CPSC4910-Team24
            git pull origin main

            cd /features/backend/about_service
            npm install --production
            pm2 restart about_service

            cd ../application_service
            npm install --production
            pm2 restart application_service_prod

